version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=sword
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
    volumes:
      - mysql_data:/var/lib/mysql

  otel-lgtm:
    image: grafana/otel-lgtm:latest
    ports:
      - "3000:3000"   # Grafana
      - "3100:3100"   # Loki
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
      - "9090:9090"   # Prometheus
    environment:
      - GRAFANA_ADMIN_PASSWORD=admin
    volumes:
      - otel_data:/var/lib/otel-lgtm

volumes:
  redis_data:
  rabbitmq_data:
  mysql_data:
  otel_data: