apiVersion: apps/v1
kind: Deployment
metadata:
  name: sword-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sword-api
  template:
    metadata:
      labels:
        app: sword-api
    spec:
      containers:
        - name: sword-api
          image: sword-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: database_url
            - name: REDIS_URL
              value: redis://redis:6379
            - name: RABBITMQ_URL
              value: amqp://admin:admin@rabbitmq:5672
            - name: PEPPER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: pepper
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: jwt_secret
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: sword-api
spec:
  selector:
    app: sword-api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
stringData:
  database_url: mysql://root:password@mysql:3306/sword
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  pepper: "your-secure-pepper-value"
  jwt_secret: "your-secure-jwt-secret"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi